from morpheus.common.infrastructure.event_sourcing.EventStore import EventStore
from morpheus.project.infrastructure.persistence.ProjectEventRepository import project_event_repository

project_event_store = EventStore(repository=project_event_repository)
