stages:
  - test
  - build
  - deploy

test:
  stage: test
  image: node:20
  script:
    - npm install --legacy-peer-deps
    - npm run test:coverage
    - npm run depcruise:app
  artifacts:
    paths:
      - coverage/lcov.info
    expire_in: 7 days

build:frontend:
  stage: build
  image: node:20
  needs:
    - test
  script:
    - npm install --legacy-peer-deps
    - npm run build
  artifacts:
    paths:
      - dist
    expire_in: 7 days
  only:
    - task/2267-dockerfile-frontend-application

deploy:frontend:
  stage: deploy
  image: docker:20.10.16-dind
  needs:
    - test
    - build:frontend
  dependencies:
    - build:frontend
  variables:
    # Use TLS https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#tls-enabled
    DOCKER_HOST: tcp://docker:2376
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - docker info
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_TOKEN $CI_REGISTRY
  script:
    - docker build --tag $CI_REGISTRY_IMAGE:$CI_ --tag $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - docker push $CI_REGISTRY_IMAGE:latest
  artifacts:
    paths:
      - dist
    expire_in: 7 days
  only:
    - task/2267-dockerfile-frontend-application
