[default]

[development]
POSTGRES_DB="inowas"
POSTGRES_USER="dev"
POSTGRES_HOST="127.0.0.1"
POSTGRES_PORT=5432
MONGO_INITDB_ROOT_USERNAME="dev"
MONGO_INITDB_ROOT_PASSWORD="dev"
MONGO_HOST="127.0.0.1"
MONGO_PORT=27017
MONGO_USER="dev"
MONGO_PASSWORD="dev"

[production]
POSTGRES_DB="inowas"
POSTGRES_USER="dev"
POSTGRES_HOST="127.0.0.1"
POSTGRES_PORT=5432
MONGO_INITDB_ROOT_USERNAME="dev"
MONGO_INITDB_ROOT_PASSWORD="dev"
MONGO_HOST="127.0.0.1"
MONGO_PORT=27017
MONGO_USER="dev"
MONGO_PASSWORD="dev"

[testing]
POSTGRES_DB="inowas"
POSTGRES_USER="dev"
POSTGRES_HOST="127.0.0.1"
POSTGRES_PORT=5432
MONGO_INITDB_ROOT_USERNAME="dev"
MONGO_INITDB_ROOT_PASSWORD="dev"
MONGO_HOST="127.0.0.1"
MONGO_PORT=27017
MONGO_USER="dev"
MONGO_PASSWORD="dev"
