stages:
  - test
  - build
  - publish
  - deploy

image: docker:20.10.16

services:
  - docker:20.10.16-dind
  - node:20

variables:
  # Use TLS https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#tls-enabled
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_CERTDIR: "/certs"

test-frontend:
  image: node:20
  stage: test

  script:
    - cd frontend
    - make install-ci
    - make test-ci

build-frontend:dev:
  image: node:20
  stage: build

  script:
    - cd frontend
    - make install-ci
    - make build

  artifacts:
    paths:
      - frontend/dist/
    expire_in: 1 days

  only:
    - main

publish-frontend:dev:
  stage: publish
  dependencies:
    - build-frontend:dev

  before_script:
    - docker info
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_TOKEN $CI_REGISTRY
  script:
    - cd frontend
    - docker build --tag $CI_REGISTRY_IMAGE_FRONTEND:$CI_COMMIT_SHA --tag $CI_REGISTRY_IMAGE_FRONTEND:dev .
    - docker push $CI_REGISTRY_IMAGE_FRONTEND:$CI_COMMIT_SHA
    - docker push $CI_REGISTRY_IMAGE_FRONTEND:dev
  only:
      - main

deploy-frontend:dev:
  image: ubuntu:22.04
  stage: deploy
  dependencies:
    - build-frontend:dev

  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - mkdir -p ~/.ssh
    - eval $(ssh-agent -s)
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - ssh-add <(echo "$SSH_PRIVATE_KEY_DEVELOPMENT")
    - apt-get install rsync -y
  script:
    - ssh -p22 $SSH_CREDENTIALS_DEVELOPMENT_SERVER "mkdir -p $DEVELOPMENT_PATH.tmp/"
    - rsync -rav -e ssh ./frontend/dist/ $SSH_CREDENTIALS_DEVELOPMENT_SERVER:/$DEVELOPMENT_PATH.tmp/
    - ssh -p22 $SSH_CREDENTIALS_DEVELOPMENT_SERVER "mv $DEVELOPMENT_PATH $DEVELOPMENT_PATH.old"
    - ssh -p22 $SSH_CREDENTIALS_DEVELOPMENT_SERVER "mv $DEVELOPMENT_PATH.tmp $DEVELOPMENT_PATH"
    - ssh -p22 $SSH_CREDENTIALS_DEVELOPMENT_SERVER "rm -rf $DEVELOPMENT_PATH.old"
  environment:
    name: development
    url: https://dev.morpheus.inowas.com
  only:
    - main

build-frontend:prod:
  image: node:20
  stage: build
  script:
    - cd frontend
    - make install-ci
    - make build
  artifacts:
    paths:
      - frontend/dist/
    expire_in: 7 days
  only:
    - tags

publish-frontend:prod:
  stage: publish
  dependencies:
    - build-frontend:prod

  before_script:
    - docker info
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_TOKEN $CI_REGISTRY
  script:
    - cd frontend
    - docker build --tag $CI_REGISTRY_IMAGE_FRONTEND:$CI_COMMIT_SHA --tag $CI_REGISTRY_IMAGE_FRONTEND:$CI_COMMIT_TAG --tag $CI_REGISTRY_IMAGE_FRONTEND:latest .
    - docker push $CI_REGISTRY_IMAGE_FRONTEND:$CI_COMMIT_SHA
    - docker push $CI_REGISTRY_IMAGE_FRONTEND:$CI_COMMIT_TAG
    - docker push $CI_REGISTRY_IMAGE_FRONTEND:latest
  only:
    - tags

deploy-frontend:prod:staging:
  stage: deploy
  dependencies:
    - build-frontend:prod
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - mkdir -p ~/.ssh
    - eval $(ssh-agent -s)
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - ssh-add <(echo "$SSH_PRIVATE_KEY_STAGING")
    - apt-get install rsync -y
  script:
    - ssh -p22 $SSH_CREDENTIALS_STAGING_SERVER "mkdir -p $STAGING_PATH.tmp/"
    - rsync -rav -e ssh ./frontend/dist/ $SSH_CREDENTIALS_STAGING_SERVER:/$STAGING_PATH.tmp/
    - ssh -p22 $SSH_CREDENTIALS_STAGING_SERVER "mv $STAGING_PATH $STAGING_PATH.old"
    - ssh -p22 $SSH_CREDENTIALS_STAGING_SERVER "mv $STAGING_PATH.tmp $STAGING_PATH"
    - ssh -p22 $SSH_CREDENTIALS_STAGING_SERVER "rm -rf $STAGING_PATH.old"
  environment:
    name: staging
    url: https://staging.morpheus.inowas.com
  only:
    - tags

deploy-frontend:prod:production:
  stage: deploy
  dependencies:
    - build-frontend:prod
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - mkdir -p ~/.ssh
    - eval $(ssh-agent -s)
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - ssh-add <(echo "$SSH_PRIVATE_KEY_PRODUCTION")
    - apt-get install rsync -y
  script:
    - ssh -p22 $SSH_CREDENTIALS_PRODUCTION_SERVER "mkdir -p $PRODUCTION_PATH.tmp/"
    - rsync -rav -e ssh ./frontend/dist/ $SSH_CREDENTIALS_PRODUCTION_SERVER:/$PRODUCTION_PATH.tmp/
    - ssh -p22 $SSH_CREDENTIALS_PRODUCTION_SERVER "mv $PRODUCTION_PATH $PRODUCTION_PATH.old"
    - ssh -p22 $SSH_CREDENTIALS_PRODUCTION_SERVER "mv $PRODUCTION_PATH.tmp $PRODUCTION_PATH"
    - ssh -p22 $SSH_CREDENTIALS_PRODUCTION_SERVER "rm -rf $PRODUCTION_PATH.old"
  environment:
    name: production
    url: https://morpheus.inowas.com
  when: manual
  only:
    - tags
