stages:
  - test
  - build
  - publish
  - deploy

image: docker:20.10.16

services:
  - docker:20.10.16-dind
  - node:20

variables:
  # Use TLS https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#tls-enabled
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_CERTDIR: "/certs"

# Frontend
include:
  - local: src/frontend/.gitlab-ci.tests.yml
  - local: src/frontend/.gitlab-ci.morpheus.yml
  - local: src/frontend/.gitlab-ci.mfviz.yml
