stages:
  - "test (unit)"
  - "test (integration)"
  - build
  - publish
  - deploy

cache:
  - key: npm
    policy: pull-push
    paths:
      - .npm/
  - key: node_modules
    policy: pull-push
    paths:
      - src/frontend/node_modules/

image: docker:20.10.16

services:
  - docker:20.10.16-dind
  - node:20

variables:
  # Use TLS https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#tls-enabled
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_CERTDIR: "/certs"
  MORPHEUS_DEVELOPMENT_PATH: /srv/docker/morpheus.development
  MORPHEUS_PRODUCTION_PATH: /srv/docker/morpheus.production

include:
  # Frontend
  - local: src/frontend/.gitlab-ci.tests.yml
  - local: src/frontend/.gitlab-ci.morpheus.yml
  - local: src/frontend/.gitlab-ci.simpletools.yml
  - local: src/frontend/.gitlab-ci.mfviz.yml
  - local: src/frontend/.gitlab-ci.storybook.yml

  # Backend
  - local: src/backend/.gitlab-ci.integration.yml
  - local: src/backend/.gitlab-ci.publish.yml

  # Keycloak
  - local: src/keycloak/.gitlab-ci.publish.yml

# Infrastructure
deploy-morpheus:dev:
  image: ubuntu:22.04
  stage: deploy
  needs:
    - job: test-morpheus-backend-integration
    - job: test-morpheus-backend-unit
    - job: publish-morpheus-backend-api:dev
      optional: true
    - job: publish-morpheus-backend-task-queue-worker:dev
      optional: true
    - job: publish-morpheus-frontend:dev
      optional: true
  before_script:
    - apt-get update && apt-get install rsync -y
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - mkdir -p ~/.ssh
    - eval $(ssh-agent -s)
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - printf '\n' >> "$SSH_PRIVATE_KEY_DEVELOPMENT"
    - chmod 600 "$SSH_PRIVATE_KEY_DEVELOPMENT"
    - ssh-add "$SSH_PRIVATE_KEY_DEVELOPMENT"
  script:
    - scp -P22 ./infrastructure/production/inowas-suite/docker-compose.yml inowas@$URL_DEVELOPMENT_SERVER:/srv/docker/inowas-suite.development/docker-compose.yml
    - ssh -p22 inowas@$URL_DEVELOPMENT_SERVER "cd /srv/docker/inowas-suite.development && docker compose pull"
    - ssh -p22 inowas@$URL_DEVELOPMENT_SERVER "cd /srv/docker/inowas-suite.development && docker compose up -d --force-recreate --remove-orphans && docker image prune -f"
  environment:
    name: development
    url: https://modflow.inowas-dev.com
  only:
    - main
    - tags

deploy-morpheus:prod:
  image: ubuntu:22.04
  stage: deploy
  needs:
    - job: test-morpheus-backend-integration
      optional: true
    - job: publish-morpheus-backend-api:prod
      optional: true
    - job: publish-morpheus-backend-task-queue-worker:prod
      optional: true
    - job: publish-morpheus-frontend:prod
      optional: true
  before_script:
    - apt-get update && apt-get install rsync -y
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - mkdir -p ~/.ssh
    - eval $(ssh-agent -s)
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
  script:
    - ssh -p22 inowas@$URL_PRODUCTION_SERVER "cd $MORPHEUS_PRODUCTION_PATH && docker compose down --remove-orphans"
    - scp -P22 ./infrastructure/production/morpheus/docker-compose.yml inowas@$URL_PRODUCTION_SERVER:/$MORPHEUS_PRODUCTION_PATH
    - scp -P22 -r ./infrastructure/production/morpheus/cron inowas@$URL_PRODUCTION_SERVER:/$MORPHEUS_PRODUCTION_PATH
    - ssh -p22 inowas@$URL_PRODUCTION_SERVER "cd $MORPHEUS_PRODUCTION_PATH && docker compose pull"
    - ssh -p22 inowas@$URL_PRODUCTION_SERVER "cd $MORPHEUS_PRODUCTION_PATH && docker compose up -d --force-recreate --remove-orphans && docker image prune -f"
  environment:
    name: production
    url: https://api.morpheus.inowas.com
  only:
    - tags
