---
"$schema": http://json-schema.org/draft-07/schema#
title: Schema for Calculation Commands
definitions:
  commands:
    AddCalculationProfileCommand:
      type: object
      properties:
        command_name:
          type: string
          enum:
            - add_calculation_profile_command
          example: add_calculation_profile_command
        payload:
          type: object
          properties:
            project_id:
              type: string
              example: e3b3b3b3-3b3b-3b3b-3b3b-3b3b3b3b3b3b
            calculation_profile_name:
              type: string
              example: calculation_profile_name
            calculation_profile_engine:
              type: string
              enum:
                - mf2005
                - mf6
                - seawat
                - mt3dms
              example: mf2005
          required:
            - project_id
            - calculation_profile_name
            - calculation_profile_engine
    DeleteCalculationCommand:
      type: object
      properties:
        command_name:
          type: string
          enum:
            - delete_calculation_command
          example: delete_calculation_command
        payload:
          type: object
          properties:
            project_id:
              type: string
              example: e3b3b3b3-3b3b-3b3b-3b3b-3b3b3b3b3b3b
            calculation_id:
              type: string
              example: e3b3b3b3-3b3b-3b3b-3b3b-3b3b3b3b3b3b
          required:
            - project_id
            - calculation_id
    RemoveCalculationProfileCommand:
      type: object
      properties:
        command_name:
          type: string
          enum:
            - remove_calculation_profile_command
          example: remove_calculation_profile_command
        payload:
          type: object
          properties:
            project_id:
              type: string
              example: e3b3b3b3-3b3b-3b3b-3b3b-3b3b3b3b3b3b
            calculation_profile_id:
              type: string
              example: e3b3b3b3-3b3b-3b3b-3b3b-3b3b3b3b3b3b
          required:
            - project_id
            - calculation_profile_id
    StartCalculationCommand:
      type: object
      properties:
        command_name:
          type: string
          enum:
            - start_calculation_command
          example: start_calculation_command
        payload:
          type: object
          properties:
            project_id:
              type: string
              example: e3b3b3b3-3b3b-3b3b-3b3b-3b3b3b3b3b3b
            model_id:
              type: string
              example: e3b3b3b3-3b3b-3b3b-3b3b-3b3b3b3b3b3b
          required:
            - project_id
            - model_id
    StopCalculationCommand:
      type: object
      properties:
        command_name:
          type: string
          enum:
            - stop_calculation_command
          example: stop_calculation_command
        payload:
          type: object
          properties:
            project_id:
              type: string
              example: e3b3b3b3-3b3b-3b3b-3b3b-3b3b3b3b3b3b
            calculation_id:
              type: string
              example: e3b3b3b3-3b3b-3b3b-3b3b-3b3b3b3b3b3b
          required:
            - project_id
            - calculation_id
    UpdateCalculationProfileCommand:
      type: object
      properties:
        command_name:
          type: string
          enum:
            - update_calculation_profile_command
          example: update_calculation_profile_command
        payload:
          type: object
          properties:
            project_id:
              type: string
              example: e3b3b3b3-3b3b-3b3b-3b3b-3b3b3b3b3b3b
            calculation_profile_id:
              type: string
              example: e3b3b3b3-3b3b-3b3b-3b3b-3b3b3b3b3b3b
            calculation_profile:
              "$ref": "#/components/Mf2005CalculationProfile"
          required:
            - project_id
            - calculation_profile_id
            - calculation_profile
components:
  Mf2005CalculationProfile:
    type: object
    properties:
      id:
        type: string
        example: e3b3b3b3-3b3b-3b3b-3b3b-3b3b3b3b3b3b
      name:
        type: string
        example: calculation_profile_name
      engine_type:
        type: string
        enum:
          - mf2005
        example: mf2005
      engine_settings:
        type: object
        properties:
          mf:
            type: object
            properties:
              verbose:
                type: boolean
                example: false
          dis:
            type: object
          bas:
            type: object
            properties:
              ichflg:
                type: boolean
                example: false
              hnoflo:
                type: number
                example: -999.99
              stoper:
                oneOf:
                  - type: 'null'
                  - type: number
          chd:
            type: object
          drn:
            type: object
            properties:
              ipakcb:
                type: integer
                example: 0
          evt:
            type: object
            properties:
              ipakcb:
                type: integer
                example: 0
              nevtop:
                type: integer
                example: 1
          fhb:
            type: object
            properties:
              ipakcb:
                type: integer
                example: 0
              ifhbss:
                type: integer
                example: 0
              ifhbpt:
                type: integer
                example: 0
          ghb:
            type: object
            properties:
              ipakcb:
                type: integer
                example: 0
          lak:
            type: object
            properties:
              ipakcb:
                type: integer
                example: 0
              theta:
                type: number
                example: 1.0
          rch:
            type: object
            properties:
              ipakcb:
                type: integer
                example: 0
          riv:
            type: object
            properties:
              ipakcb:
                type: integer
                example: 0
          wel:
            type: object
            properties:
              ipakcb:
                type: integer
                example: 0
          hob:
            type: object
            properties:
              iuhobsv:
                type: integer
                example: 0
              hobdry:
                type: number
                example: 0.0
          selected_flow_package:
            type: string
            enum:
              - bcf
              - lpf
            example: lpf
          bcf:
            type: object
            properties:
              ipakcb:
                type: integer
                example: 0
              iwdflg:
                type: integer
                example: 0
              ihdwet:
                type: integer
                example: 0
              wetfct:
                type: number
                example: 0.1
              iwetit:
                type: integer
                example: 1
              wetdry:
                type: number
                example: -0.01
              hdry:
                type: number
                example: -1e+30
          lpf:
            type: object
            properties:
              ipakcb:
                type: integer
                example: 0
              iwdflg:
                oneOf:
                  - type: integer
                  - type: array
                    items:
                      type: integer
                example: 0
              ihdwet:
                type: integer
                example: 0
              wetfct:
                type: number
                example: 0.1
              iwetit:
                type: integer
                example: 1
              wetdry:
                type: number
                example: -0.01
              hdry:
                type: number
                example: -1e+30
              storagecoefficient:
                type: boolean
                example: false
              nocvcorrection:
                type: boolean
                example: false
              constantcv:
                type: boolean
                example: false
              novfc:
                type: boolean
                example: false
              thickstrt:
                type: boolean
                example: false
          selected_solver_package:
            type: string
            enum:
              - de4
              - gmg
              - pcg
              - pcgn
              - sip
            example: pcg
          de4:
            type: object
            properties:
              itmx:
                type: integer
                example: 50
              mxup:
                type: integer
                example: 0
              mxlow:
                type: integer
                example: 0
              mxbw:
                type: integer
                example: 0
              ifreq:
                type: integer
                example: 3
              mutd4:
                type: integer
                example: 0
              accl:
                type: integer
                example: 1
              hclose:
                type: number
                example: 1e-05
              iprd4:
                type: integer
                example: 1
          gmg:
            type: object
            properties:
              mxiter:
                type: integer
                example: 50
              iiter:
                type: integer
                example: 30
              iadamp:
                type: integer
                example: 0
              hclose:
                type: number
                example: 1e-05
              rclose:
                type: number
                example: 1e-05
              relax:
                type: number
                example: 1.0
              ioutgmg:
                type: integer
                example: 0
              iunitmhc:
                type: integer
                example: 0
              ism:
                type: integer
                example: 0
              isc:
                type: integer
                example: 0
              damp:
                type: number
                example: 1.0
              dup:
                type: number
                example: 0.75
              dlow:
                type: number
                example: 0.01
              chglimit:
                type: number
                example: 1.0
          pcg:
            type: object
            properties:
              mxiter:
                type: integer
                example: 50
              iter1:
                type: integer
                example: 30
              npcond:
                type: integer
                example: 1
              hclose:
                type: number
                example: 1e-05
              rclose:
                type: number
                example: 1e-05
              relax:
                type: number
                example: 1.0
              nbpol:
                type: integer
                example: 0
              iprpcg:
                type: integer
                example: 0
              mutpcg:
                type: integer
                example: 3
              damp:
                type: number
                example: 1.0
              dampt:
                type: number
                example: 1.0
              ihcofadd:
                type: integer
                example: 0
          pcgn:
            type: object
            properties:
              iter_mo:
                type: integer
                example: 50
              iter_mi:
                type: integer
                example: 30
              close_r:
                type: number
                example: 1e-05
              close_h:
                type: number
                example: 1e-05
              relax:
                type: number
                example: 1.0
              ifill:
                type: integer
                example: 0
              unit_pc:
                type: integer
                example: 0
              unit_ts:
                type: integer
                example: 3
              adamp:
                type: integer
                example: 0
              damp:
                type: number
                example: 1.0
              damp_lb:
                type: number
                example: 0.001
              rate_d:
                type: number
                example: 0.1
              chglimit:
                type: number
                example: 0.0
              acnvg:
                type: integer
                example: 0
              cnvg_lb:
                type: number
                example: 0.001
              mcnvg:
                type: integer
                example: 2
              rate_c:
                type: number
                example: -1.0
              ipunit:
                type: integer
                example: 0
          sip:
            type: object
            properties:
              mxiter:
                type: integer
                example: 200
              nparm:
                type: integer
                example: 5
              accl:
                type: number
                example: 1.0
              hclose:
                type: number
                example: 1e-05
              ipcalc:
                type: integer
                example: 1
              wseed:
                type: number
                example: 0.0
              iprsip:
                type: integer
                example: 0
          oc:
            type: object
            properties:
              ihedfm:
                type: integer
                example: 0
              iddnfm:
                type: integer
                example: 0
              chedfm:
                oneOf:
                  - type: 'null'
                  - type: string
                example: null
              cddnfm:
                oneOf:
                  - type: 'null'
                  - type: string
                example: null
              cboufm:
                oneOf:
                  - type: 'null'
                  - type: string
                example: null
              compact:
                type: boolean
                example: true
              label:
                type: string
                example: "OC"
