openapi: 3.1.0
info:
  title: INOWAS API
  version: 2.0.0
paths:
  /sensors:
    get:
      tags:
        - Sensor
      summary: Read list of sensors
      description: Read list of sensors
      responses:
        200:
          description: List of sensors
          content:
            application/json:
              schema:
                type: array
        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: Not found
