version: "3.8"
services:
  frontend:
    image: inowas/morpheus-frontend:${FRONTEND_VERSION}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend-http.entrypoints=web"
      - "traefik.http.routers.frontend-http.rule=Host(`${FRONTEND_HOST}`)"
      - "traefik.http.routers.frontend-http.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.permanent=true"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.rule=Host(`${FRONTEND_HOST}`)"
      - "traefik.http.routers.frontend.tls=true"
      - "traefik.http.routers.frontend.tls.certresolver=myresolver"
      - "traefik.http.services.frontend.loadbalancer.server.port=8080"
      - "traefik.docker.network=traefik-web-gateway"
    restart: always
    read_only: true
    tmpfs:
      - /var/run:mode=777,size=100m
      - /var/cache/nginx:mode=777,size=100m
#  backend:
#    image: inowas/morpheus-backend:${BACKEND_VERSION}
#    depends_on:
#      - mongo
#      - postgres
#    environment:
#      DYNACONF_SECRET_KEY: ${SECRET_KEY}
#      DYNACONF_POSTGRES_USER: ${POSTGRES_USER}
#      DYNACONF_POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#      DYNACONF_POSTGRES_DB: ${POSTGRES_DB}
#      DYNACONF_POSTGRES_HOST: ${POSTGRES_HOST}
#      DYNACONF_POSTGRES_PORT: ${POSTGRES_PORT}
#      DYNACONF_MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
#      DYNACONF_MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
#      DYNACONF_MONGO_HOST: ${MONGO_HOST}
#    labels:
#      - "traefik.enable=true"
#      - "traefik.http.routers.frontend-http.entrypoints=web"
#      - "traefik.http.routers.frontend-http.rule=Host(`${BACKEND_HOST}`)"
#      - "traefik.http.routers.frontend-http.middlewares=redirect-to-https"
#      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
#      - "traefik.http.middlewares.redirect-to-https.redirectscheme.permanent=true"
#      - "traefik.http.routers.frontend.entrypoints=websecure"
#      - "traefik.http.routers.frontend.rule=Host(`${BACKEND_HOST}`)"
#      - "traefik.http.routers.frontend.tls=true"
#      - "traefik.http.routers.frontend.tls.certresolver=myresolver"
#      - "traefik.http.services.frontend.loadbalancer.server.port=8000"
#      - "traefik.docker.network=traefik-web-gateway"
#    restart: always
#    user: flask
#    read_only: true
#  postgres:
#    image: postgres:13.12
#    environment:
#      POSTGRES_USER: ${POSTGRES_USER}
#      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#      POSTGRES_DB: ${POSTGRES_DB}
#    volumes:
#      - ./db/postgres:/var/lib/postgresql/data
#    restart: always
#  mongo:
#    image: mongo:5.0
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
#      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
#    volumes:
#      - ./db/mongo:/data/db
#    restart: always

networks:
  default:
    name: traefik-web-gateway
    external: true
