from .CloneModelLayer import CloneModelLayerCommand, CloneModelLayerCommandHandler
from .CreateModelLayer import CreateModelLayerCommand, CreateModelLayerCommandHandler
from .DeleteModelLayer import DeleteModelLayerCommand, DeleteModelLayerCommandHandler
from .UpdateModelLayerConfinement import UpdateModelLayerConfinementCommand, UpdateModelLayerConfinementCommandHandler
from .UpdateModelLayerMetadata import UpdateModelLayerMetadataCommand, UpdateModelLayerMetadataCommandHandler
from .UpdateModelLayerOrder import UpdateModelLayerOrderCommand, UpdateModelLayerOrderCommandHandler
from .UpdateModelLayerPropertyDefaultValue import UpdateModelLayerPropertyDefaultValueCommand, UpdateModelLayerPropertyDefaultValueCommandHandler
from .UpdateModelLayerPropertyRasterReference import UpdateModelLayerPropertyRasterReferenceCommand, UpdateModelLayerPropertyRasterReferenceCommandHandler
from .UpdateModelLayerPropertyZones import UpdateModelLayerPropertyZonesCommand, UpdateModelLayerPropertyZonesCommandHandler

model_layers_command_handler_map = {
    CloneModelLayerCommand: CloneModelLayerCommandHandler,
    CreateModelLayerCommand: CreateModelLayerCommandHandler,
    DeleteModelLayerCommand: DeleteModelLayerCommandHandler,
    UpdateModelLayerConfinementCommand: UpdateModelLayerConfinementCommandHandler,
    UpdateModelLayerMetadataCommand: UpdateModelLayerMetadataCommandHandler,
    UpdateModelLayerOrderCommand: UpdateModelLayerOrderCommandHandler,
    UpdateModelLayerPropertyDefaultValueCommand: UpdateModelLayerPropertyDefaultValueCommandHandler,
    UpdateModelLayerPropertyRasterReferenceCommand: UpdateModelLayerPropertyRasterReferenceCommandHandler,
    UpdateModelLayerPropertyZonesCommand: UpdateModelLayerPropertyZonesCommandHandler,
}
