version: "3.8"
services:
  traefik:
    image: traefik:v2.10
    command:
      - "--log.level=INFO"
      - "--log.filePath=/var/logs/traefik/traefik.log"
      - "--accesslog=true"
      - "--api=false"
      - "--api.dashboard=false"
      - "--api.insecure=false"
      - "--entryPoints.web.address=:80"
      - "--entryPoints.websecure.address=:443"
      - "--global.checkNewVersion=true"
      - "--global.sendAnonymousUsage=false"
      - "--providers.docker=true"
      - "--providers.docker.exposedByDefault=false"
      # Let's Encrypt
      - "--certificatesresolvers.letsencrypt.acme.tlschallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.caserver=${TRAEFIK_ACME_LETSENCRYPT_CASERVER}"
      - "--certificatesresolvers.letsencrypt.acme.email=${TRAEFIK_ACME_EMAIL}"
      - "--certificatesresolvers.letsencrypt.acme.storage=/etc/traefik/acme/acme_letsencrypt.json"
      # TU-Dresden CA
      - "--certificatesresolvers.tud-resolver.acme.tlschallenge=true"
      - "--certificatesresolvers.tud-resolver.acme.caserver=${TRAEFIK_ACME_TUD_CASERVER}"
      - "--certificatesresolvers.tud-resolver.acme.email=${TRAEFIK_ACME_EMAIL}"
      - "--certificatesresolvers.tud-resolver.acme.eab.kid=${TRAEFIK_ACME_TUD_EAB_KID}"
      - "--certificatesresolvers.tud-resolver.acme.eab.hmacencoded=${TRAEFIK_ACME_TUD_EAB_HMAC_ENCODED}"
      - "--certificatesresolvers.tud-resolver.acme.storage=/etc/traefik/acme/acme_tud.json"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./acme:/etc/traefik/acme
      - ./logs:/var/logs/traefik
    ports:
      - "80:80"
      - "443:443"
    restart: always
    networks:
      - traefik
    read_only: true
networks:
  traefik:
    name: ${TRAEFIK_NETWORK}
    external: true
