openapi: 3.0.0
info:
  title: INOWAS API
  version: 2.0.0

servers:
  - url: /api/v2
    description: INOWAS API

paths:
  /auth/oauth/token:
    post:
      summary: Get OAuth2 Token
      description: 'Fetch a new access and refresh token. Supported grant types are: password and refresh_token.'
      requestBody:
        content:
          application/json:
            schema:
              oneOf:
                - $ref: '#/components/schemas/OAuthPasswordGrantRequest'
                - $ref: '#/components/schemas/OAuthRefreshTokenGrantRequest'
      responses:
        200:
          description: Successful token response
          content:
            application/json:
              schema:
                type: object
                properties:
                  access_token:
                    type: string
                    example: 'JZeXaGRgCOdIIjeyLmk8BM6oVVr9QZNWR5IaMDxoG1'
                  token_type:
                    type: string
                    example: 'Bearer'
                  expires_in:
                    type: integer
                    example: 864000
                  refresh_token:
                    type: string
                    example: 'OWlrhuK4dIQy6957lZoAA4COBpjwaBEuRWD6dTgnmTsdCVQX'
        400:
          description: Invalid grant type, client, username/password or invalid request

  /auth/oauth/revoke:
    post:
      summary: Revoke OAuth2 Token
      description: 'Revoke an access and refresh token.'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                client_id:
                  $ref: '#/components/schemas/OAuthClientId'
                token:
                  type: string
                  description: "The access token to revoke"
                  example: "JZeXaGRgCOdIIjeyLmk8BM6oVVr9QZNWR5IaMDxoG1"
                token_type_hint:
                  enum:
                    - access_token
      responses:
        200:
          description: Token was successfully revoked
          content:
            application/json:
              schema:
                type: object
        400:
          description: Invalid client or invalid request

  /user/me:
    get:
      summary: User Info
      description: Get the user info.
      security:
        - bearerAuth: [ ]
      responses:
        200:
          description: Successful user info response.
          content:
            application/json:
              schema:
                type: object
                properties:
                  email:
                    type: string
                    example: "example@inowas.com"
        401:
          description: Unauthorized

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer

  schemas:
    OAuthPasswordGrantRequest:
      type: object
      properties:
        grant_type:
          enum:
            - password
        client_id:
          $ref: '#/components/schemas/OAuthClientId'
        username:
          type: string
        password:
          type: string
      required:
        - grant_type
        - client_id
        - username
        - password
      example:
        {
          grant_type: "password",
          client_id: "0d37fdf4-03bd-40f1-832d-46099ecc93bc",
          username: "example@inowas.com",
          password: "my secret password"
        }

    OAuthRefreshTokenGrantRequest:
      type: object
      description: "The Request to retrieve a new OAuth-Token from a Refresh-Token."
      properties:
        grant_type:
          enum:
            - refresh_token
        client_id:
          $ref: '#/components/schemas/OAuthClientId'
        refresh_token:
          type: string
          description: "Your refresh token."
      required:
        - grant_type
        - client_id
        - refresh_token
      example:
        {
          grant_type: "refresh_token",
          client_id: "0d37fdf4-03bd-40f1-832d-46099ecc93bc",
          refresh_token: "OWlrhuK4dIQy6957lZoAA4COBpjwaBEuRWD6dTgnmTsdCVQX"
        }

    OAuthClientId:
      type: string
      description: "The oauth2 client_id"
      example: "0d37fdf4-03bd-40f1-832d-46099ecc93bc"
