version: "3.8"
services:
  traefik:
    image:
      traefik:2.10
    command:
      - "--log.level=DEBUG"
      - "--accesslog=true"
      - "--api=true"
      - "--api.dashboard=true"
      - "--api.insecure=true"
      - "--api.debug=true"
      - "--ping=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.postgres.address=:5432"
      - "--entrypoints.mongodb.address=:27017"
      - "--providers.docker=true"
      - "--providers.docker.exposedByDefault=false"
      - "--providers.file.directory=/etc/traefik"
      - "--providers.file.watch=true"
      - "--global.checkNewVersion=true"
      - "--global.sendAnonymousUsage=false"
      - "--log.filePath=/var/log/traefik/traefik.log"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080" # for traefik api, dashboard and healthcheck (development only)
      - "5432:5432" # for postgres (development only)
      - "27017:27017" # for mongodb (development only)
    healthcheck:
      test: [ "CMD", "traefik", "healthcheck", "--ping" ]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik:/etc/traefik
      - ./tls_certificates:/etc/tls_certificates
    environment:
      - TLS_KEY_FILE=${TLS_KEY_FILE}
      - TLS_CERT_FILE=${TLS_CERT_FILE}
    networks:
      - auth
      - backend
      - mail
  #  frontend:
  #    build:
  #      context: ${PWD}
  #      dockerfile: frontend/docker/Dockerfile
  #    restart: always
  #    ports:
  #      - "8080:8080"
  backend:
    build:
      context: ${MORPHEUS_PROJECT_ROOT}
      dockerfile: src/backend/docker/Dockerfile.development
      args:
        - MKCERT_ROOT_CA_CERTIFICATE=infrastructure/development/tls_certificates/rootCA.pem
        - CAROOT=/etc/ca_root
        - FLASK_USER_ID=${FLASK_USER_ID}
        - FLASK_GROUP_ID=${FLASK_GROUP_ID}
      target: development
    depends_on:
      mongodb_backend:
        condition: service_healthy
      postgres_backend:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - CAROOT=/etc/ca_root # for development only
    volumes:
      - ${MORPHEUS_PROJECT_ROOT}/src/backend:/app
      - ./data/morpheus/sensors:${BACKEND_MORPHEUS_SENSORS_LOCAL_DATA}:rw
    restart: always
    user: flask
    read_only: true
    command: [ "flask", "run", "--host=0.0.0.0", "--port=8000" ]
    networks:
      - backend
    extra_hosts:
      - identity.inowas.localhost:host-gateway
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-backend-http.entrypoints=web"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-backend-http.rule=Host(`${BACKEND_HOST}`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-backend-http.middlewares=redirect-to-https@file"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-backend.entrypoints=websecure"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-backend.rule=Host(`${BACKEND_HOST}`)"
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}-backend.loadbalancer.server.port=8000"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-backend.tls=true"
  mongodb_backend:
    image: mongo:7.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${BACKEND_MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${BACKEND_MONGO_INITDB_ROOT_PASSWORD}
    env_file:
      - .env
    volumes:
      - mongodb_backend_data:/data/db
      - ./mongodb_backend/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.runCommand('ping').ok", "--quiet" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always
    networks:
      - backend
    read_only: true
    user: mongodb
    tmpfs:
      - /tmp
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.${COMPOSE_PROJECT_NAME}-mongodb_backend.entrypoints=mongodb"
      - "traefik.tcp.routers.${COMPOSE_PROJECT_NAME}-mongodb_backend.rule=HostSNI(`*`)"
      - "traefik.tcp.services.${COMPOSE_PROJECT_NAME}-mongodb_backend.loadbalancer.server.port=27017"
  postgres_backend:
    image: postgres:13.12
    environment:
      POSTGRES_USER: ${BACKEND_POSTGRES_USER}
      POSTGRES_PASSWORD: ${BACKEND_POSTGRES_PASSWORD}
      POSTGRES_DB: ${BACKEND_POSTGRES_DB}
    volumes:
      - postgres_backend_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U ${BACKEND_POSTGRES_USER} -d ${BACKEND_POSTGRES_DB}'" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always
    read_only: true
    networks:
      - backend
    tmpfs:
      - /tmp
      - /var/run/postgresql
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.${COMPOSE_PROJECT_NAME}-postgres_backend.entrypoints=postgres"
      - "traefik.tcp.routers.${COMPOSE_PROJECT_NAME}-postgres_backend.rule=HostSNI(`*`)"
      - "traefik.tcp.services.${COMPOSE_PROJECT_NAME}-postgres_backend.loadbalancer.server.port=5432"
  mailcatcher:
    image: sj26/mailcatcher:latest
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-mailcatcher.entrypoints=web"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-mailcatcher.rule=Host(`mailcatcher.${DOMAIN}`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-mailcatcher.tls=false"
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}-mailcatcher.loadbalancer.server.port=1080"
    networks:
      - mail
  keycloak:
    build:
      context: ${MORPHEUS_PROJECT_ROOT}
      dockerfile: src/keycloak/Dockerfile
      target: development
    environment:
      KC_DB: postgres
      KC_DB_PASSWORD: ${KEYCLOAK_POSTGRES_PASSWORD}
      KC_DB_URL: jdbc:postgresql://postgres_keycloak:5432/${KEYCLOAK_POSTGRES_DB}
      KC_DB_USERNAME: ${KEYCLOAK_POSTGRES_USER}
      KC_HOSTNAME_URL: https://${IDENTITY_HOST}
      KC_PROXY: edge
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      QUARKUS_TRANSACTION_MANAGER_ENABLE_RECOVERY: true # https://github.com/keycloak/keycloak/issues/15255
    command:
      start --optimized --import-realm
    networks:
      - auth
      - mail
    depends_on:
      postgres_keycloak:
        condition: service_healthy
    read_only: true
    tmpfs:
      - /tmp
    volumes:
      - keycloak_data:/opt/keycloak/data
      - ./keycloak:/opt/keycloak/data/import # for development only
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-keycloak-http.entrypoints=web"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-keycloak-http.rule=Host(`${IDENTITY_HOST}`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-keycloak-http.middlewares=redirect-to-https@file"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-keycloak.entrypoints=websecure"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-keycloak.rule=Host(`${IDENTITY_HOST}`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-keycloak.tls=true"
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}-keycloak.loadbalancer.server.port=8080"
  postgres_keycloak:
    image: postgres:13.12
    environment:
      POSTGRES_USER: ${KEYCLOAK_POSTGRES_USER}
      POSTGRES_PASSWORD: ${KEYCLOAK_POSTGRES_PASSWORD}
      POSTGRES_DB: ${KEYCLOAK_POSTGRES_DB}
    volumes:
      - postgres_keycloak_data:/var/lib/postgresql/data
    read_only: true
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U ${KEYCLOAK_POSTGRES_USER} -d ${KEYCLOAK_POSTGRES_DB}'" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always
    networks:
      - auth
    tmpfs:
      - /tmp
      - /var/run/postgresql
volumes:
  keycloak_data:
    driver: local
  postgres_keycloak_data:
    driver: local
  postgres_backend_data:
    driver: local
  mongodb_backend_data:
    driver: local
  morpheus_sensor_data:
    driver: local
networks:
  auth:
    name: ${COMPOSE_PROJECT_NAME}-auth
  backend:
    name: ${COMPOSE_PROJECT_NAME}-backend
  mail:
    name: ${COMPOSE_PROJECT_NAME}-mail
