test-frontend:
  image: node:20
  stage: test

  script:
    - cd src/frontend
    - make install-ci
    - make test-ci
  rules:
    - if: $CI_COMMIT_BRANCH
      changes:
        compare_to: 'refs/heads/main'
        paths:
          - src/frontend/**/*
