test-frontend:
  image: node:20
  stage: test

  script:
    - cd src/frontend
    - make install-ci
    - make test-ci
  rules:
    - changes:
        compare_to: main
        paths:
          - src/frontend/**/*
