test-frontend:
  image: node:20
  stage: test

  script:
    - cd src/frontend
    - make install-ci
    - make test-ci

  only:
    changes:
      - src/frontend/src/**/*.*
      - src/frontend/package.json
      - src/frontend/package-lock.json
