openapi: 3.1.0
info:
  title: INOWAS API
  version: 2.0.0
  description: INOWAS API

servers:
  - url: http://127.0.0.1:5000
    description: Local Development API
  - url: http://localhost:5000
    description: Local Development API
  - url: http://api.morpheus.inowas.localhost
    description: Local API
  - url: http://api.morpheus.inowas.com
    description: Deveoplment API
  - url: http://api.dev.morpheus.inowas.com
    description: Production API
  - url: https://api.morpheus.inowas.com
    description: Production API

paths:
  /projects:
    $ref: './project/openapi.yml#/paths/~1projects'

  /projects/messagebox:
    $ref: './project/openapi.yml#/paths/~1projects~1messagebox'

  /projects/{project_id}/model:
    $ref: './project/openapi.yml#/paths/~1projects~1{project_id}~1model'

  /projects/{project_id}/model/spatial-discretization:
    $ref: './project/openapi.yml#/paths/~1projects~1{project_id}~1model~1spatial-discretization'

  /projects/{project_id}/model/spatial-discretization/geometry:
    $ref: './project/openapi.yml#/paths/~1projects~1{project_id}~1model~1spatial-discretization~1geometry'

  /projects/{project_id}/model/spatial-discretization/grid:
    $ref: './project/openapi.yml#/paths/~1projects~1{project_id}~1model~1spatial-discretization~1grid'

  /projects/{project_id}/model/time-discretization:
    $ref: './project/openapi.yml#/paths/~1projects~1{project_id}~1model~1time-discretization'

  /projects/{project_id}/permissions:
    $ref: './project/openapi.yml#/paths/~1projects~1{project_id}~1preview_image'

  /projects/{project_id}/preview_image:
    $ref: './project/openapi.yml#/paths/~1projects~1{project_id}~1preview_image'

  /projects/{project_id}/assets:
    $ref: './project/openapi.yml#/paths/~1projects~1{project_id}~1assets'

  /projects/{project_id}/assets/{asset_id}:
    $ref: './project/openapi.yml#/paths/~1projects~1{project_id}~1assets~1{asset_id}'

  /projects/{project_id}/assets/{asset_id}/file:
    $ref: './project/openapi.yml#/paths/~1projects~1{project_id}~1assets~1{asset_id}~1file'

  /projects/{project_id}/assets/{asset_id}/data:
    $ref: './project/openapi.yml#/paths/~1projects~1{project_id}~1assets~1{asset_id}~1data'

  /sensors:
    $ref: './sensor/openapi.yml#/paths/~1sensors'

  /users:
    $ref: './user/openapi.yml#/paths/~1users'

  /users/groups:
    $ref: './user/openapi.yml#/paths/~1users~1groups'

  /users/groups/{group_id}/members:
    $ref: './user/openapi.yml#/paths/~1users~1groups~1{group_id}~1members'

  /users/groups/{group_id}/members/{user_id}:
    $ref: './user/openapi.yml#/paths/~1users~1groups~1{group_id}~1members~1{user_id}'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerAuth: [ ]
