openapi: 3.1.0
info:
  title: INOWAS API
  version: 2.0.0

servers:
  - url: http://localhost:5000
    description: Local Development API
  - url: https://api.morpheus.inowas.com
    description: Production API

paths:
  /modflow:
    get:
      tags:
        - Modflow
      summary: Read list of modflow models
      description: Read list of modflow models
      responses:
        200:
          description: List of modflow models
          content:
            application/json:
              schema:
                type: array
        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: Not found
    post:
      tags:
        - Modflow
      summary: Create a new modflow model
      description: Create a new modflow model
      requestBody:
        content:
          application/json:
            schema:
              $ref: './modflow/openapi.yml#/components/schemas/CreateModflowModelRequest'
      responses:
        201:
          description: Modflow model was successfully created
        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: Not found

  /sensors:
    get:
      tags:
        - Sensors
      summary: Read list od sensors
      description: Read list of sensors
      responses:
        200:
          description: List of sensors
          content:
            application/json:
              schema:
                type: array
        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: Not found

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
    -   bearerAuth: [ ]

