openapi: 3.1.0
info:
  title: INOWAS API
  version: 2.0.0

servers:
  - url: http://localhost:5000
    description: Local Development API
  - url: https://api.morpheus.inowas.com
    description: Production API

paths:
  /modflow:
    $ref: './modflow/openapi.yml#/paths/~1modflow'

  /modflow/{project_id}:
    $ref: './modflow/openapi.yml#/paths/~1modflow~1{project_id}'

  /modflow/{project_id}/base_model:
    $ref: './modflow/openapi.yml#/paths/~1modflow~1{project_id}~1base_model'

  /sensors:
    $ref: './sensors/openapi.yml#/paths/~1sensors'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerAuth: [ ]
