openapi: 3.1.0
info:
  title: INOWAS API
  version: 2.0.0

servers:
  - url: http://127.0.0.1:5000
    description: Local Development API
  - url: http://localhost:5000
    description: Local Development API
  - url: http://api.morpheus.inowas.localhost
    description: Local API
  - url: https://api.morpheus.inowas.com
    description: Production API

paths:
  /projects:
    $ref: './project/openapi.yml#/paths/~1projects'

  /projects/{project_id}:
    $ref: './project/openapi.yml#/paths/~1projects~1{project_id}'

  /projects/{project_id}/model:
    $ref: './project/openapi.yml#/paths/~1projects~1{project_id}~1model'

  /projects/{project_id}/preview_image:
    $ref: './project/openapi.yml#/paths/~1projects~1{project_id}~1preview_image'

  /projects/{project_id}/assets:
    $ref: './project/openapi.yml#/paths/~1projects~1{project_id}~1assets'

  /projects/{project_id}/assets/{asset_id}:
    $ref: './project/openapi.yml#/paths/~1projects~1{project_id}~1assets~1{asset_id}'

  /projects/{project_id}/assets/{asset_id}/file:
    $ref: './project/openapi.yml#/paths/~1projects~1{project_id}~1assets~1{asset_id}~1file'

  /projects/{project_id}/assets/{asset_id}/data:
    $ref: './project/openapi.yml#/paths/~1projects~1{project_id}~1assets~1{asset_id}~1data'

  /sensors:
    $ref: './sensor/openapi.yml#/paths/~1sensors'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerAuth: [ ]
