version: "3.8"
services:
  keycloak:
    image: inowas/keycloak:${KEYCLOAK_VERSION}
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_DB: postgres
      KC_DB_USERNAME: ${KEYCLOAK_POSTGRES_USER}
      KC_DB_PASSWORD: ${KEYCLOAK_POSTGRES_PASSWORD}
      KC_DB_URL: jdbc:postgresql://postgres_keycloak:5432/${KEYCLOAK_POSTGRES_DB}
      KC_PROXY: edge
      KC_HOSTNAME_URL: ${KEYCLOAK_HOSTNAME}
      QUARKUS_TRANSACTION_MANAGER_ENABLE_RECOVERY: true # https://github.com/keycloak/keycloak/issues/15255
    command:
      start --optimized
    networks:
      - auth
      - traefik
    depends_on:
      postgres_keycloak:
        condition: service_healthy
    read_only: true
    tmpfs:
      - /tmp
    volumes:
      - keycloak_data:/opt/keycloak/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-keycloak-http.entrypoints=web"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-keycloak-http.rule=Host(`${DOMAIN}`)"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.permanent=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-keycloak-http.middlewares=redirect-to-https"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-keycloak.entrypoints=websecure"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-keycloak.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-keycloak.tls=true"
      # comment out the following line to disable letsencrypt
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-keycloak.tls.certresolver=letsencrypt"
      # uncomment the following lines to enable TU-Dresden CA
      # - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-keycloak.tls.certresolver=myresolver"
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}-keycloak.loadbalancer.server.port=8080"
      - "traefik.docker.network=${TRAEFIK_NETWORK}"
  postgres_keycloak:
    image: postgres:13.12
    environment:
      POSTGRES_USER: ${KEYCLOAK_POSTGRES_USER}
      POSTGRES_PASSWORD: ${KEYCLOAK_POSTGRES_PASSWORD}
      POSTGRES_DB: ${KEYCLOAK_POSTGRES_DB}
    volumes:
      - postgres_keycloak_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${KEYCLOAK_POSTGRES_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always
    networks:
      - auth
    read_only: true
    tmpfs:
      - /tmp
      - /var/run/postgresql
volumes:
  keycloak_data:
    driver: local
  postgres_keycloak_data:
    driver: local
networks:
  auth:
      name: ${COMPOSE_PROJECT_NAME}-auth
  traefik:
    name: ${TRAEFIK_NETWORK}
    external: true
