---
"$schema": http://json-schema.org/draft-07/schema#
title: Schema for ModelDiscretizationCommands
definitions:
  commands:
    UpdateModelAffectedCellsCommand:
      type: object
      properties:
        command_name:
          type: string
          enum:
            - update_model_affected_cells_command
          example: update_model_affected_cells_command
        payload:
          properties:
            project_id:
              type: string
              example: e3b3b3b3-3b3b-3b3b-3b3b-3b3b3b3b3b3b
            affected_cells:
              "$ref": "#/definitions/components/AffectedCells"
          required:
            - project_id
            - affected_cells
    UpdateModelGeometryCommand:
      type: object
      properties:
        command_name:
          type: string
          enum:
            - update_model_geometry_command
          example: update_model_geometry_command
        payload:
          properties:
            project_id:
              type: string
              example: e3b3b3b3-3b3b-3b3b-3b3b-3b3b3b3b3b3b
            geometry:
              "$ref": "#/definitions/components/Polygon"
          required:
            - project_id
            - geometry
      required:
        - command_name
        - payload
    UpdateModelGridCommand:
      type: object
      properties:
        command_name:
          type: string
          enum:
            - update_model_grid_command
          example: update_model_grid_command
        payload:
          properties:
            project_id:
              type: string
              example: e3b3b3b3-3b3b-3b3b-3b3b-3b3b3b3b3b3b
            n_cols:
              type: integer
              minimum: 1
              maximum: 1000
            n_rows:
              type: integer
              minimum: 1
              maximum: 1000
            origin:
              "$ref": "#/definitions/components/Point"
            col_widths:
              type: array
              items:
                type: number
            total_width:
              type: number
            row_heights:
              type: array
              items:
                type: number
            total_height:
              type: number
            rotation:
              type: number
              minimum: -90
              maximum: 90
            length_unit:
              type: string
              enum:
                - meters
                - centimeters
                - feet
                - unknown
          required:
            - project_id
            - n_cols
            - n_rows
    UpdateModelTimeDiscretizationCommand:
      type: object
      properties:
        command_name:
          type: string
          enum:
            - update_model_time_discretization_command
          example: update_model_time_discretization_command
        payload:
          properties:
            project_id:
              type: string
              example: e3b3b3b3-3b3b-3b3b-3b3b-3b3b3b3b3b3b
            start_date_time:
              type: string
              format: date-time
            end_date_time:
              type: string
              format: date-time
            stress_periods:
              type: array
              items:
                type: object
                properties:
                  start_date_time:
                    type: string
                    format: date-time
                  number_of_time_steps:
                    type: integer
                    minimum: 1
                    maximum: 1000
                  time_step_multiplier:
                    type: number
                    minimum: 0.0001
                    maximum: 1000
                  steady_state:
                    type: boolean
            time_unit:
              type: string
              enum:
                - seconds
                - minutes
                - hours
                - days
                - years
          required:
            - project_id
            - start_date_time
            - end_date_time
            - stress_periods
            - time_unit
  components:
    AffectedCells:
      type: object
    AffectedLayers:
      type: array
      items:
        $ref: "#/definitions/components/LayerId"
    LayerId:
      type: string
      example: e3b3b3b3-3b-3b-3b-3b-3b3b-3b3b3b3b3b3b
    MultiPolygon:
      type: object
      description: The geometry of the feature.
      properties:
        type:
          type: string
          enum:
            - MultiPolygon
          example: MultiPolygon
        coordinates:
          type: array
          description: The coordinates of the geometry.
          example:
            - - - - 13.922514437551428
                  - 50.964720483303836
                - - 13.925250781947113
                  - 50.965228748412386
                - - 13.925036413951403
                  - 50.96623732041704
                - - 13.92222441026388
                  - 50.96609040370362
                - - 13.922514437551428
                  - 50.964720483303836
          items:
            type: array
            items:
              type: array
              items:
                type: array
                items:
                  type: number
                  minItems: 2
                  maxItems: 2
      required:
        - type
        - coordinates
    Nullable:
      type: 'null'
    Linestring:
      type: object
      description: The geometry of the feature.
      properties:
        type:
          type: string
          enum:
            - LineString
          example: LineString
        coordinates:
          type: array
          description: The coordinates of the geometry.
          items:
            type: array
            items:
              type: number
            minItems: 2
            maxItems: 2
          example:
            - - 13.922514437551428
              - 50.964720483303836
            - - 13.925250781947113
              - 50.965228748412386
            - - 13.925036413951403
              - 50.96623732041704
            - - 13.92222441026388
              - 50.96609040370362
            - - 13.922514437551428
              - 50.964720483303836
      required:
        - type
        - coordinates
    Point:
      type: object
      description: The geometry of the feature.
      properties:
        type:
          type: string
          enum:
            - Point
          example: Point
        coordinates:
          type: array
          description: The coordinates of the geometry.
          example:
            - 13.922514437551428
            - 50.964720483303836
          items:
            type: number
            minItems: 2
            maxItems: 2
      required:
        - type
        - coordinates
    Polygon:
      type: object
      description: The geometry of the feature.
      properties:
        type:
          type: string
          enum:
            - Polygon
          example: Polygon
        coordinates:
          type: array
          description: The coordinates of the geometry.
          items:
            type: array
            items:
              type: array
              items:
                type: number
                minItems: 2
                maxItems: 2
          example:
            - - - 13.922514437551428
                - 50.964720483303836
              - - 13.925250781947113
                - 50.965228748412386
              - - 13.925036413951403
                - 50.96623732041704
              - - 13.92222441026388
                - 50.96609040370362
              - - 13.922514437551428
                - 50.964720483303836
      required:
        - type
        - coordinates
