apiVersion: v1
kind: ConfigMap
metadata:
  name: website-content
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>My Static Website</title>
    </head>
    <body>
    <h1>Welcome to My Static Website</h1>
    </body>
    </html>
