openapi: 3.1.0
info:
  title: INOWAS API - Modflow Module
  version: 2.0.0
components:
  schemas:
    CreateModflowModelRequest:
      type: object
      description: "The Request to create a new ModflowModel."
      properties:
        name:
          type: string
          description: "The name of the model."
          example: "My first model"
        description:
          type: string
          description: "The description of the model."
          example: "This is my first model"
        tags:
          type: array
          description: "The tags of the model."
          items:
            type: string
          example: [ "tag1", "tag2" ]
        geometry:
          type: object
          description: "The geometry of the feature."
          properties:
            type:
              type: string
              enum: [ "Polygon" ]
              example: "Polygon"
            coordinates:
              type: array
              description: "The coordinates of the geometry."
              example: [ [ [ 13.0, 51.0 ], [ 13.0, 51.1 ], [ 13.1, 51.1 ], [ 13.1, 51.0 ], [ 13.0, 51.0 ] ] ]
              items:
                type: array
                items:
                  type: array
                  items:
                    type: number
                    minItems: 2
                    maxItems: 2
          required:
            - type
            - coordinates
        grid_properties:
          type: object
          description: "The grid properties of the model."
          properties:
            x_coordinates:
              type: array
              description: "The distance along the x axis in percent."
              example: [ 0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0 ]
              items:
                type: number
                minimum: 0
                maximum: 1
            y_coordinates:
              type: array
              description: "The distance along the y axis in percent."
              example: [ 0, 0.2, 0.4, 0.6, 0.8, 1.0 ]
              items:
                type: number
                minimum: 0
                maximum: 1
            rotation:
              type: number
              description: "The grid rotation angle in deg of the model."
              minimum: -90
              maximum: 90
              example: 0.0
            length_unit:
              type: string
              enum: [ "meters", "centimeters", "feet", "unknown" ]
              example: "meters"
          required:
            - x_coordinates
            - y_coordinates
            - rotation
            - length_unit

      required:
        - name
        - description
        - tags
        - geometry
        - grid_properties

