from .AddModelBoundary import AddModelBoundaryCommand, AddModelBoundaryCommandHandler
from .AddModelBoundaryObservation import AddModelBoundaryObservationCommand, AddModelBoundaryObservationCommandHandler
from .AddModelObservation import AddModelObservationCommand, AddModelObservationCommandHandler
from .CloneModelBoundary import CloneModelBoundaryCommand, CloneModelBoundaryCommandHandler
from .CloneModelBoundaryObservation import CloneModelBoundaryObservationCommand, CloneModelBoundaryObservationCommandHandler
from .CloneModelLayer import CloneModelLayerCommand, CloneModelLayerCommandHandler
from .CloneModelObservation import CloneModelObservationCommand, CloneModelObservationCommandHandler
from .CreateModel import CreateModelCommand, CreateModelCommandHandler
from .CreateModelLayer import CreateModelLayerCommand, CreateModelLayerCommandHandler
from .CreateModelVersion import CreateModelVersionCommand, CreateModelVersionCommandHandler
from .DeleteModelVersion import DeleteModelVersionCommand, DeleteModelVersionCommandHandler
from .DeleteModelLayer import DeleteModelLayerCommand, DeleteModelLayerCommandHandler
from .DisableModelBoundary import DisableModelBoundaryCommandHandler, DisableModelBoundaryCommand
from .DisableModelObservation import DisableModelObservationCommand, DisableModelObservationCommandHandler
from .EnableModelBoundary import EnableModelBoundaryCommand, EnableModelBoundaryCommandHandler
from .EnableModelObservation import EnableModelObservationCommand, EnableModelObservationCommandHandler
from .RemoveModelBoundary import RemoveModelBoundaryCommand, RemoveModelBoundaryCommandHandler
from .RemoveModelBoundaryObservation import RemoveModelBoundaryObservationCommandHandler, RemoveModelBoundaryObservationCommand
from .RemoveModelObservation import RemoveModelObservationCommand, RemoveModelObservationCommandHandler
from .UpdateModelBoundaryAffectedCells import UpdateModelBoundaryAffectedCellsCommand, UpdateModelBoundaryAffectedCellsCommandHandler
from .UpdateModelBoundaryAffectedLayers import UpdateModelBoundaryAffectedLayersCommandHandler, UpdateModelBoundaryAffectedLayersCommand
from .UpdateModelBoundaryGeometry import UpdateModelBoundaryGeometryCommandHandler, UpdateModelBoundaryGeometryCommand
from .UpdateModelBoundaryInterpolation import UpdateModelBoundaryInterpolationCommand, UpdateModelBoundaryInterpolationCommandHandler
from .UpdateModelBoundaryMetadata import UpdateModelBoundaryMetadataCommandHandler, UpdateModelBoundaryMetadataCommand
from .UpdateModelBoundaryObservation import UpdateModelBoundaryObservationCommandHandler, UpdateModelBoundaryObservationCommand
from .UpdateModelLayerConfinement import UpdateModelLayerConfinementCommand, UpdateModelLayerConfinementCommandHandler
from .UpdateModelLayerMetadata import UpdateModelLayerMetadataCommand, UpdateModelLayerMetadataCommandHandler
from .UpdateModelLayerOrder import UpdateModelLayerOrderCommand, UpdateModelLayerOrderCommandHandler
from .UpdateModelLayerPropertyDefaultValue import UpdateModelLayerPropertyDefaultValueCommand, UpdateModelLayerPropertyDefaultValueCommandHandler
from .UpdateModelLayerPropertyRasterReference import UpdateModelLayerPropertyRasterReferenceCommand, UpdateModelLayerPropertyRasterReferenceCommandHandler
from .UpdateModelLayerPropertyZones import UpdateModelLayerPropertyZonesCommand, UpdateModelLayerPropertyZonesCommandHandler
from .UpdateModelAffectedCells import UpdateModelAffectedCellsCommand, UpdateModelAffectedCellsCommandHandler
from .UpdateModelGeometry import UpdateModelGeometryCommand, UpdateModelGeometryCommandHandler
from .UpdateModelGrid import UpdateModelGridCommand, UpdateModelGridCommandHandler
from .UpdateModelTimeDiscretization import UpdateModelTimeDiscretizationCommand, UpdateModelTimeDiscretizationCommandHandler
from .UpdateModelVersionDescription import UpdateModelVersionDescriptionCommand, UpdateModelVersionDescriptionCommandHandler

model_command_handler_map = {
    AddModelBoundaryCommand: AddModelBoundaryCommandHandler,
    AddModelBoundaryObservationCommand: AddModelBoundaryObservationCommandHandler,
    AddModelObservationCommand: AddModelObservationCommandHandler,
    CloneModelBoundaryCommand: CloneModelBoundaryCommandHandler,
    CloneModelBoundaryObservationCommand: CloneModelBoundaryObservationCommandHandler,
    CloneModelObservationCommand: CloneModelObservationCommandHandler,
    CloneModelLayerCommand: CloneModelLayerCommandHandler,
    CreateModelCommand: CreateModelCommandHandler,
    CreateModelLayerCommand: CreateModelLayerCommandHandler,
    CreateModelVersionCommand: CreateModelVersionCommandHandler,
    DeleteModelLayerCommand: DeleteModelLayerCommandHandler,
    DeleteModelVersionCommand: DeleteModelVersionCommandHandler,
    DisableModelBoundaryCommand: DisableModelBoundaryCommandHandler,
    DisableModelObservationCommand: DisableModelObservationCommandHandler,
    EnableModelBoundaryCommand: EnableModelBoundaryCommandHandler,
    EnableModelObservationCommand: EnableModelObservationCommandHandler,
    RemoveModelBoundaryCommand: RemoveModelBoundaryCommandHandler,
    RemoveModelBoundaryObservationCommand: RemoveModelBoundaryObservationCommandHandler,
    RemoveModelObservationCommand: RemoveModelObservationCommandHandler,
    UpdateModelAffectedCellsCommand: UpdateModelAffectedCellsCommandHandler,
    UpdateModelBoundaryAffectedCellsCommand: UpdateModelBoundaryAffectedCellsCommandHandler,
    UpdateModelBoundaryAffectedLayersCommand: UpdateModelBoundaryAffectedLayersCommandHandler,
    UpdateModelBoundaryGeometryCommand: UpdateModelBoundaryGeometryCommandHandler,
    UpdateModelBoundaryInterpolationCommand: UpdateModelBoundaryInterpolationCommandHandler,
    UpdateModelBoundaryMetadataCommand: UpdateModelBoundaryMetadataCommandHandler,
    UpdateModelBoundaryObservationCommand: UpdateModelBoundaryObservationCommandHandler,
    UpdateModelGeometryCommand: UpdateModelGeometryCommandHandler,
    UpdateModelGridCommand: UpdateModelGridCommandHandler,
    UpdateModelLayerConfinementCommand: UpdateModelLayerConfinementCommandHandler,
    UpdateModelLayerMetadataCommand: UpdateModelLayerMetadataCommandHandler,
    UpdateModelLayerOrderCommand: UpdateModelLayerOrderCommandHandler,
    UpdateModelLayerPropertyDefaultValueCommand: UpdateModelLayerPropertyDefaultValueCommandHandler,
    UpdateModelLayerPropertyRasterReferenceCommand: UpdateModelLayerPropertyRasterReferenceCommandHandler,
    UpdateModelLayerPropertyZonesCommand: UpdateModelLayerPropertyZonesCommandHandler,
    UpdateModelTimeDiscretizationCommand: UpdateModelTimeDiscretizationCommandHandler,
    UpdateModelVersionDescriptionCommand: UpdateModelVersionDescriptionCommandHandler,
}
